baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[taxonomies]
  tag = "tags"
  category = "categories"
  growth = "growth"
  connects_to = "connects_to"
  builds_on = "builds_on"
  challenges = "challenges"
  # Epistemic Status
  certainty = "certainty"
  evidence = "evidence"
  # Maintenance Status
  freshness = "freshness"
  completeness = "completeness"
  # Thematic Clustering
  mindset = "mindset"
  domain = "domain"

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
