baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Garden'

[menus]
  [[menus.main]]
    name = 'Garden'
    identifier = 'garden'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Notes'
    parent = 'garden'
    pageRef = '/notes'
    weight = 20
  
  [[menus.main]]
    name = 'Essays'
    parent = 'garden'
    pageRef = '/essays'
    weight = 21

  [[menus.main]]
    name = 'Bookmarks'
    parent = 'garden'
    pageRef = '/bookmarks'
    weight = 22

  [[menus.main]]
    name = 'Portraits'
    parent = 'garden'
    pageRef = '/portraits'
    weight = 23

  [[menus.main]]
    name = 'Projects'
    parent = 'garden'
    pageRef = '/projects'
    weight = 24

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
  
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
